"""add url and image_url to Car

Revision ID: 482f37a5a451
Revises: 
Create Date: 2025-04-29 01:58:16.023623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482f37a5a451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
