"""Add sales field to Car

Revision ID: dfbc0f1dab65
Revises: 482f37a5a451
Create Date: 2025-04-29 16:18:52.556857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbc0f1dab65'
down_revision = '482f37a5a451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('sales')

    # ### end Alembic commands ###
