"""Add car static info

Revision ID: e3c2c8f929c6
Revises: bc4076f451fd
Create Date: 2025-05-20 17:35:43.533891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c2c8f929c6'
down_revision = 'bc4076f451fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('battery_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('range_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('autopilot_level', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('autopilot_level')
        batch_op.drop_column('range_km')
        batch_op.drop_column('battery_type')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
